MixinNetwork/flutter-app

lib/app.dart
lib/utils/system/text_input.dart

a workaround for https://github.com/flutter/flutter/issues/78061

add a workaround for TextField delete on macOS.

---

lib/ui/home/chat/input_container.dart

Reverts MixinNetwork/flutter-app#512

Revert "clear input history when input message has sent."

---

pubspec.lock
pubspec.yaml

fix https://github.com/MixinNetwork/flutter-plugins/issues/72

upgrade desktop_drop version

---

lib/ui/home/chat/chat_bar.dart
lib/ui/home/chat_slide_page/group_participants_page.dart
lib/ui/home/chat_slide_page/search_message_page.dart
lib/ui/home/command_palette_wrapper.dart
lib/ui/home/conversation/search_list.dart
lib/ui/home/slide_page.dart
lib/ui/setting/edit_profile_page.dart
lib/ui/setting/setting_page.dart
lib/widgets/avatar_view/avatar_view.dart
lib/widgets/mention_panel.dart
lib/widgets/message/item/contact_message_widget.dart
lib/widgets/message/item/image/image_preview_page.dart
lib/widgets/message/item/quote_message.dart
lib/widgets/message/message.dart
lib/widgets/user/user_dialog.dart
lib/widgets/user_selector/conversation_selector.dart

Improve contact message.

---

lib/ui/home/conversation/network_status.dart

show `LinearProgressIndicator` when connecting/reconnecting.
improve network indicator display on app launch.

improve network status bar

---

lib/widgets/message/item/transcript_message.dart
lib/workers/message_worker_isolate.dart
pubspec.lock

`updateMessageContentAndStatus` when send message cause transcript has a bad content which can not be display.

fix send transcript message

---

lib/workers/message_worker_isolate.dart
lib/workers/sender.dart

fix plain transcript/location/live messagesend

Fix plain message send

---

lib/utils/hook.dart
lib/widgets/message/item/action_card/action_message.dart
lib/widgets/message/item/image/image_message.dart
pubspec.lock

Improve action message.

---

lib/account/account_server.dart
lib/db/dao/message_dao.dart
lib/utils/attachment/attachment_util.dart
lib/workers/message_worker_isolate.dart

Fix recive attachment message error

---

pubspec.lock
pubspec.yaml

fix wrong playback speed on some devices.

bump ogg_opus_player to 0.3.2

---

lib/utils/file.dart

Reverts MixinNetwork/flutter-app#302  
This doesn't need anymore.

Revert "change app document dir  on windows. "

---

lib/ui/home/chat/files_preview.dart
lib/ui/home/chat/image_editor.dart

1. always show edit button on mobile platforms.
2. fix custom paint line width in editor.

improve image editor

---

lib/widgets/sticker_page/emoji_page.dart

remove the emojis which has skin.
for example:   ☝️☝🏻☝🏼☝🏽☝🏾☝🏿   ->  keep ☝️ only.

remove modifiable emojis

---

lib/db/dao/snapshot_dao.g.dart
lib/db/dao/transcript_message_dao.g.dart
lib/db/mixin_database.dart
lib/db/mixin_database.g.dart
lib/db/moor/mixin.drift
macos/Podfile.lock
pubspec.lock

Users.IdentityNumber is missing indexes, which makes the query slow.

Improve mention query

---

lib/db/dao/message_dao.dart
macos/Podfile.lock
pubspec.lock

The #750 introduced an issue that caused a query message after query error.

Fix message after

---

lib/utils/hive_key_values.dart

Fix refactor hiveKeyValues file to account path.

---

lib/workers/message_worker_isolate.dart

Fix dio does not serialize Iterable
Add sessoin ack log

Fix send ack and add session ack log

---

lib/account/notification_service.dart

uri body are case insensitive. so move the conversation_id to query parameter to avoid case transformed.

fix conversation_id case transformed in notification url

---

.github/workflows/manual-build.yml
dist/deb/DEBIAN/control
dist/linux_deb.sh

1. remove unnecessary sqlite lib copy.  since sqlite3_flutter_libs already included it. https://pub.dev/packages/sqlite3_flutter_libs/changelog#055
2. remove VLC denpends, add libsdl2 depends.
3. auto update the version info in control file from pubspec.yaml

Improve linux deb build

---

lib/generated/intl/messages_en.dart
lib/generated/intl/messages_zh.dart
lib/generated/l10n.dart
lib/l10n/intl_en.arb
lib/l10n/intl_zh.arb
lib/ui/home/chat/input_container.dart
lib/ui/home/chat/voice_recorder_bottom_bar.dart
pubspec.lock
pubspec.yaml

when recording voice, if user click the outside of `VoiceRecorderBottomBar`, display a discard warning dialog.

add discard warning on recording voice.

---

lib/utils/extension/src/string.dart
test/db/database_fts5_search_test.dart
test/utils/string_extension_test.dart

fix fts5 search number and alphabet.

---

lib/main.dart

see https://github.com/bitsdojo/bitsdojo_window/issues/193

add temp solution for windows white screen

---

lib/main.dart

https://docs.flutter.dev/testing/errors#handling-all-types-of-errors

migrate to new flutter error handler.

---

pubspec.lock
pubspec.yaml

fix notification wired app name when app package as msix.

bump win_toast version to 0.1.0

---

lib/ui/home/home.dart
lib/ui/home/slide_page.dart
lib/utils/platform.dart
lib/widgets/window/move_window.dart
pubspec.lock
pubspec.yaml

make sure always display drawer on iPhone devices.

improve ui on iPhone

---

lib/widgets/message_status_icon.dart

1. pause animation if window unfoucse / icon is invisible.
2. replace Ticker to Timer, reduce animation frame count.

improve animated sending icon performance

---

.github/workflows/dart.yml
.github/workflows/manual-build.yml
AppImageBuilder.yml
README.md
dist/deb/DEBIAN/control
dist/snap/snap/snapcraft.yaml

linux add libopus0 dependency

---

.github/workflows/manual-build.yml
lib/utils/message_optimize.dart
lib/widgets/user/pin_verification_dialog.dart

example: https://github.com/boyan01/flutter-app/releases/tag/v0.37.1
assets:
- mixin_desktop_linux_amd64.AppImage
- mixin_desktop_linux_amd64.deb
- mixin_desktop_linux_amd64.flatpak
- mixin_desktop_linux_amd64.snap
- mixin_desktop_linux_amd64_portable.tar.gz
- mixin_desktop_windows_setup_amd64.exe

Auto upload build artifacts to assets when release published

---

pubspec.lock
pubspec.yaml

fix audio message recorder might not work properly sometimes.

bump ogg_opus_player to 0.6.4

---

lib/utils/extension/src/file.dart
lib/widgets/cache_image.dart
lib/widgets/cache_lottie.dart
pubspec.lock
pubspec.yaml

fix CI broken https://github.com/MixinNetwork/flutter-app/actions/runs/3749159338/jobs/6397687854

Remove extend_image package

---

lib/db/dao/message_dao.dart
lib/db/mixin_database.g.dart
lib/db/moor/dao/message.drift
lib/ui/home/conversation/search_list.dart
pubspec.lock

Show correct avatar in search message list.

Fix search list

---

lib/utils/platform.dart

A workaround for https://github.com/BestBurning/platform_device_id/issues/15
details: https://github.com/BestBurning/platform_device_id/issues/15#issuecomment-1064081170

fix blink cmd window when app started on Windows

---

lib/generated/intl/messages_all.dart
pubspec.lock
pubspec.yaml

https://github.com/localizely/intl_utils/issues/90#issuecomment-1324919622

fix L10n.load caused the black frame

---

lib/widgets/dialog.dart
lib/widgets/search_text_field.dart
lib/widgets/user_selector/conversation_selector.dart

another part of https://github.com/MixinNetwork/flutter-app/pull/1066

remove textfied hint animation

---

lib/account/account_server.dart
lib/db/dao/expired_message_dao.dart
lib/db/dao/message_dao.dart
lib/db/database.dart
lib/db/database_event_bus.dart
lib/db/mixin_database.dart
lib/main.dart
lib/utils/event_bus.dart
lib/workers/isolate_event.dart
lib/workers/message_worker_isolate.dart
test/utils/event_bus_test.dart

add a global event bus implemtation which can send/listen event across isoalte.
1. refactor `DataBaseEventBus` by the new event bus
2. refactor expiredmessages table update by use `DatabaseEventBus`

Refactor event bus

---

lib/widgets/markdown.dart

improve Markdown code block style

---

lib/ui/home/chat/files_preview.dart

1. containts the `maxHeight` of `_TileBigImage` widget  to  the height of List widget.
2. auto scroll to bottom when new file/image added

improve files preview dialog UI

---

pubspec.lock
pubspec.yaml

fix
```
Run flutter pub run debug_info_collector
Unhandled exception:
PathNotFoundException: Directory listing failed, path = 'build\windows\plugins\*' (OS Error: The system cannot find the path specified.
, errno = 3)
#0      _Directory._fillWithDirectoryListing (dart:io-patch/directory_patch.dart:42:24)
#1      _Directory.listSync (dart:io/directory_impl.dart:233:5)
#2      collect (package:debug_info_collector/debug_info_collector.dart:16:[8](https://github.com/MixinNetwork/flutter-app/actions/runs/6119008194/job/16608092110#step:15:9))
<asynchronous suspension>
Error: Process completed with exit code 1.
```

fix debug info collector

---

lib/ui/home/chat/image_editor.dart
lib/ui/home/chat/input_container.dart
lib/ui/home/chat_slide_page/chat_info_page.dart
lib/widgets/menu.dart
lib/widgets/user/user_dialog.dart
pubspec.lock
pubspec.yaml

1. rafctor send type choose button popup menu, add rotate animation
2. refactor image editor crop button, share contact copy user url popup menu

Refactor PopupMenuPage button to ContextMenu
