MixinNetwork/flutter-app

lib/utils/extension/src/string.dart
fix search message with keyword `abc` can not match the text `abcdefg`
=> remove escapeFts5 unnecessary quotation marks

lib/bloc/setting_cubit.dart
`_brightness` could be `null`, which makes assertion failed on debug version.
=> fix setting brightness assertion.

lib/account/account_server.dart, lib/utils/mixin_api_client.dart
when device time has been corrected after a api request, the reponse might get a 401 error, and the local device time is correct. In this case, the current user will be logout, although the 401 error was rasied by incorrect local time.
=> use request time to check 401 error if rasied by incorrect time

lib/widgets/cache_lottie.dart, lib/widgets/sticker_page/sticker_item.dart
`Lottie.network` only cache to memory which will be cleaned after app quit. 
Add `CachedNetworkLottie` to help cache the Lottie jsons to `TemporaryDirectory()/mixin/lottie_cache` as files.
=> cache lottie to local temp directory

lib/widgets/dialog.dart
add `MediaQuery.of(context).viewInsets` to dialog padding.
make dialog can reponsive with the soft keyboard, to ensure the dialog content is not obscured by the soft keyboard.
=> improve dialog viewInsets handle

lib/ui/home/chat/input_container.dart, lib/widgets/high_light_text.dart
according https://github.com/flutter/flutter/issues/68675. we can use `includeLineSpacingMiddle` as ` SelectableText.selectionHeightStyle`
=> fix chat page text selection background box height

lib/workers/message_worker_isolate.dart
Add 1 second delay to error occurs when job processing, to avoid CPU usuage too high if error fail fast unexecpeted (eg. device network unavailable)
=> add delay when error occurs in job process

pubspec.lock, pubspec.yaml
https://github.com/MixinNetwork/flutter-plugins/commit/6f8458fed6de65bf119d4812b2186c03d8c4b7b2
fix `GetCurrentPackageFullName` didn't work on win7
=> bump win_toast to 0.1.1

lib/widgets/window/menus.dart
remove menu bar shortcut for close window action, replace by https://github.com/MixinNetwork/flutter-app/blob/main/lib/widgets/window/window_shortcuts.dart
=> fix command+w can not close webview window on macOS

.github/workflows/dart.yml, .github/workflows/manual-build.yml, analysis_options.yaml, lib/ui/home/bloc/blink_cubit.dart, lib/ui/home/bloc/mention_cubit.dart, lib/ui/home/bloc/message_bloc.dart, lib/ui/home/bloc/slide_category_state.dart, lib/ui/home/chat/chat_bar.dart, lib/ui/home/chat/input_container.dart, lib/ui/home/chat/voice_recorder_bottom_bar.dart, lib/ui/home/chat_slide_page/circle_manager_page.dart, lib/ui/home/chat_slide_page/group_invite/group_invite_dialog.dart, lib/ui/home/route/responsive_navigator_state.dart, lib/utils/system/tray.dart, lib/widgets/app_bar.dart, lib/widgets/az_selection.dart, lib/widgets/high_light_text.dart, lib/widgets/menu.dart, lib/widgets/message/item/contact_message_widget.dart, lib/widgets/sticker_page/sticker_store.dart, macos/Podfile.lock
=> Fix warning

lib/app.dart, lib/utils/system/text_input.dart
reland #535 which revoked in #559
Remove this if https://github.com/flutter/flutter/issues/111113 has been fixed.
=> Add a workaround for TextField delete on macOS. 

lib/utils/dp_utils.dart, lib/widgets/message/item/sticker_message.dart, lib/widgets/user/pin_verification_dialog.dart
set the width and height to kMaxWidth.
to avoid chat page message list can not scroll down slowly.
=> set sticker width and height to kMaxWidth

lib/utils/local_notification_center.dart, lib/widgets/protocol_handler.dart, linux/flutter/generated_plugin_registrant.cc, linux/flutter/generated_plugins.cmake, pubspec.lock, pubspec.yaml
fix window did't bring to front when click a notification or an external url
----
On wayland, if gtk window was covered by other window, it will not be brought to front by call `gtk_window_present`.
see more: https://gitlab.gnome.org/GNOME/gtk/-/issues/624
=> [linux] fix window show didn't work on wayland

lib/ui/home/bloc/conversation_list_bloc.dart
fix unhandled error:
```
unhandled error: MissingPluginException(No implementation found for method updateBadge on channel flutter_app_icon_badge) 
```
=> fix update badge throw error on other platforms

lib/account/account_server.dart
since `Duration(minutes: 5, seconds: 10).inMinutes` also return `5`.
=> fix time check in request error

lib/db/mixin_database.dart
the database's readCount in `message_worker_isolate`  is 2, but in main isolate is 4. that cause the database in `message_worker_isolate` can not do read opreation after hot restart.
=> Fix database foreground port name

lib/db/dao/conversation_dao.dart, lib/db/mixin_database.g.dart, lib/db/moor/dao/circle.drift, lib/db/moor/dao/conversation.drift, lib/ui/home/bloc/conversation_list_bloc.dart, lib/ui/home/chat/chat_page.dart, lib/ui/home/chat/input_container.dart, lib/ui/home/chat_slide_page/chat_info_page.dart, lib/ui/home/chat_slide_page/circle_manager_page.dart, lib/ui/home/chat_slide_page/group_invite/group_invite_dialog.dart, lib/ui/home/chat_slide_page/group_participants_page.dart, lib/ui/setting/storage_usage_detail_page.dart, lib/utils/hook.dart, lib/widgets/avatar_view/avatar_view.dart, lib/widgets/user/user_dialog.dart, pubspec.lock
noticed that we use always use `useMemoziedFuture(xxx).data ?? emptyValue` in `Widget#build` function. it caused the error in snapshot has been ignored. such as #981
to avoid this, add a `_logSnapshotError` to print the snapshot's error  in `useMemoziedFuture` and `useMemoizedStream`.
And fix some bug of SQL
=> log useFuture/useStream snapshot errors

lib/utils/extension/src/file.dart
FileImage(File(path)).toImage() only works in main isolate
```
flutter: When the exception was thrown, this was the stack:
flutter: #0      BindingBase.checkInstance.<anonymous closure> (package:flutter/src/foundation/binding.dart:287:9)
flutter: #1      BindingBase.checkInstance (package:flutter/src/foundation/binding.dart:369:6)
flutter: #2      PaintingBinding.instance (package:flutter/src/painting/binding.dart:31:54)
flutter: #3      ImageProvider.resolveStreamForKey (package:flutter/src/painting/image_provider.dart:511:61)
flutter: #4      ImageProvider.resolve.<anonymous closure> (package:flutter/src/painting/image_provider.dart:358:9)
flutter: #5      ImageProvider._createErrorHandlerAndKey.<anonymous closure> (package:flutter/src/painting/image_provider.dart:473:24)
flutter: #6 …
```
=> move _encodeBlurHash to main isolate

lib/db/dao/message_dao.dart, lib/ui/home/bloc/message_bloc.dart
if message has the same `createdAt` timestamp, use `rowId` as secondary order.
=> fix base message items default sort

lib/db/dao/job_dao.dart
The current behavior is consistent with android app.
see also: https://github.com/MixinNetwork/android-app/blob/04e43f3a05f9978ab9ad6c2abcfcd5fddd1c3e5d/app/src/main/java/one/mixin/android/db/JobDao.kt#L19
=> Fix query session ack job

lib/ui/provider/conversation_provider.dart
fix 
```
flutter: 2023-08-29 15:44:33.787 [E] unhandled error: Bad state: Tried to use ConversationStateNotifier after `dispose` was called.
Consider checking `mounted`.
#0      StateNotifier._debugIsMounted.<anonymous closure> (package:state_notifier/state_notifier.dart:175:9)
#1      StateNotifier._debugIsMounted (package:state_notifier/state_notifier.dart:182:6)
#2      StateNotifier.state= (package:state_notifier/state_notifier.dart:210:12)
#3      ConversationStateNotifier.selectConversation (package:flutter_app/ui/provider/conversation_provider.dart:309:26)
<asynchronous suspension>
#4      SearchList.build.<anonymous closure>.<anonymous closure>.<anonymous closure> (package:flutter_app/ui/home/conversation/search_list.dart:344:25)
<asynchronous suspension>
```
=> fix conversationProvider disposed unexpected when search conversation
